### ISSUE TITLE
NPE on RealmDataSourceFactory.updateQuery()

### ISSUE THREAD

**Issue by SergiyKorotun** [Zhuinden/realm-monarchy#16]
Hello, I got NPE when trying to use updateQuery() function. I called it immediately after dataSource creation. Here is a stack trace :
` java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zhuinden.monarchy.Monarchy$RealmTiledDataSource.invalidate()' on a null object reference
        at com.zhuinden.monarchy.PagedLiveResults.updateQuery(PagedLiveResults.java:73)
        at com.zhuinden.monarchy.Monarchy$RealmDataSourceFactory.updateQuery(Monarchy.java:645)`

Could you add a check for null? or I can submit a PR

**Comment by Zhuinden** [comment]
Huh, you can update the query even without having created a datasource? Didn't expect that. But I'll add a null check and that ought to solve it.

**Comment by Zhuinden** [comment]
Should be fixed in 0.4.3
