### ISSUE TITLE
Entire data from the DB is getting loaded into pagedlist. Is it not honoring the page size in Monarchy?

### ISSUE THREAD

**Issue by ksyamkrishnan** [Zhuinden/realm-monarchy#27]
Entire data from the DB is getting loaded into pagedlist. Is it not honoring the page size in Monarchy?
`public List<T> loadRange(final int startPosition, final int count) {
            final int countItems = countItems();
            if(countItems == 0) {
                return Collections.emptyList();
            }
            final List<T> list = new ArrayList<>(count);
            monarchy.doWithRealm(new Monarchy.RealmBlock() {
                @Override
                public void doWithRealm(Realm realm) {
                    RealmResults<T> results = (RealmResults<T>) 
                    monarchy.resultsRefs.get().get(liveResults);
                    for(int i = startPosition; i < startPosition + count && i < countItems; i++) {
                        // noinspection ConstantConditions
                        list.add(realm.copyFromRealm(results.get(i)));
                    }
                }
            });

            return Collections.unmodifiableList(list);
        }`

**Comment by Zhuinden** [comment]
Hmm? What do you mean? It definitely shouldn't be loading ALL items at once.

It should be loading a page amount, as it is read from Realm with that `for {` loop.

**Comment by ksyamkrishnan** [comment]
ok. I was not setting the value for InitialLoadSizeHint. Because of that, it was taking the first 3 pages by default.

**Comment by ksyamkrishnan** [comment]
ok. I was not setting the value for InitialLoadSizeHint. Because of that, it was taking the first 3 pages by default.
