### ISSUE TITLE
`PagedLiveResults` support (when paging lib is 1.0)

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/realm-monarchy#3]

**Comment by tudorluca** [comment]
paging lib is 1.0 😜. also, thanks for the great work!

**Comment by Zhuinden** [comment]
@lucamtudor thanks for the notice!

I've actually successfully hidden RealmResults as a positional data source, I just have to merge [the other repo sample](https://github.com/Zhuinden/room-live-paged-list-provider-experiment/tree/e76f3d2c5e1be402ff0fe2dc46e62f9e2a102080/app-realm/src/main/java/com/zhuinden/realmlivepagedlistproviderexperiment/util) into an optional module of monarchy.

Glad to see someone's actually looking out for Monarchy, I haven't really heard anything about it from anyone since I've made it and that was apparently 5 months ago 😄

**Comment by tudorluca** [comment]
@Zhuinden I'm back in the realm game after a year of firebase projects and I was looking into new best practices & stuff like that, especially with the new arch-components being so awesome and useful. Still not sure if bleeding realm into my view/view-models is such a good idea 🙂. I was hoping someone else already went through the trouble of doing all the research 😇😂, but I'm not that lucky :). Thoughts?

**Comment by Zhuinden** [comment]
@lucamtudor [Realm has an architecture components example which got squash/committed but technically I wrote it](https://github.com/realm/realm-java/blob/3529e041e2252c449c6b5f7bf1d1b2ff04781c34/examples/architectureComponentsExample/src/main/java/io/realm/examples/arch/livemodel/LiveRealmResults.java).

There are varying degrees of Realm integration, tbh, and that sample shows how to use Realm via lazy loading, while Monarchy shows how to obtain the items to memory on background thread - its true power however is unrealized until I make the commit with the paged list support.

Still, AAC is really useful because `LiveData<List<T>>` is a natural wrapper over the behavior of RealmResults.

I wrote something about this around a year ago: https://hackernoon.com/musing-on-architectural-components-and-realm-and-room-and-a-look-at-reactive-clean-architecture-880c8df55abf

**Comment by shynline** [comment]
@Zhuinden WOW 
this library(wrapper) is awesome.
I'm totally gonna switch to monarchy from realm completely.
I was looking for something like that for my last project tho.
I said that in order to encourage you to keep on working on this.
btw I'm interested in using the paging library for my new project so my question is when are you going to merge the other sample u've mentioned before? :)

**Comment by mhdtouban** [comment]
Great work, any plan to make this as a library?
I have been using realm for quite some times and am happy with it so no plan to use room any time soon, but I liked paging library features and especially the placeholder or continuous load mechanism. So I want to use paging and realm to gather.

**Comment by Zhuinden** [comment]
When I stop being a lazy bum, I have about 4 things I should be doing! :D

~~But more importantly, I need to figure out how to make Jitpack's plugin publish two library modules from this repo, because Paging has to be an additional module.~~

~~According to https://github.com/afollestad/material-dialogs/blob/1726e5b088baa180b353fed9a389c6f41942239b/core/build.gradle it should work with the schema defined in https://github.com/jitpack/jitpack.io/issues/203~~

~~`compile 'com.afollestad.material-dialogs:core:0.8.0.0'`~~

~~I'll need this as a reference for introduction of paging module.~~

----

I didn't realize people were waiting for this! I'll try to figure it out this coming week. 

I already have a *working* sample with RealmResults being queried on a background looper thread as a positional data source, so it shouldn't be *that* hard to bring it over.

~~I really was putting it off because it's like, you try to publish to Jitpack and if you mess up the publish process it just stays there o_o but gotta do it eventually anyways, might as well figure it out on this one~~

**Comment by Zhuinden** [comment]
In the end, it's not possible to make it a separate module because I actually couldn't even move them out of the Monarchy *class*. Gotta talk to a bunch of private stuff.

**But good news everyone, I've added it and it should be released as ~~0.2.0~~ 0.2.1**

Rejoice!

https://github.com/Zhuinden/realm-monarchy/commit/52ea74b1829ef500a243446286eeb5d78c2fb3e3

**Comment by Zhuinden** [comment]
@lucamtudor @mhdtouban @shayan3985 if I didn't mess anything up then you should be able to utilize the full power of AAC Paging on top of Realm :+1:

see https://github.com/Zhuinden/realm-monarchy/blob/4b60aa565cd2a322e5c542c112cd877f67991086/monarchy-example/src/main/java/com/zhuinden/monarchyexample/features/paged/PagedFragment.java#L68-L72

**Comment by Zhuinden** [comment]
Scratch that, I'll have to release a patch. -_-

**Comment by Zhuinden** [comment]
Okay, 0.2.1 should do the trick.

**Comment by mhdtouban** [comment]
@Zhuinden I'll test that tomorrow and let you know how it goes.

**Comment by Zhuinden** [comment]
@mhdtouban does it blend?

**Comment by mhdtouban** [comment]
I didn't had chance to test it, maybe tomorrow.

**Comment by shynline** [comment]
I've just tested it and it's been working perfectly so far.
Good job!

**Comment by Zhuinden** [comment]
You guys might want to update to 0.2.2 though because another guy found something stupid (albeit unrelated) that's been in there since December, but that's just how these things go :smile:
