### ISSUE TITLE
BoundaryCallback with Monarchy

### ISSUE THREAD

**Issue by stevepham** [Zhuinden/realm-monarchy#31]
Does Monarchy support BoundaryCallback? I add boundary into LivePagedListBuilder but not received any trigger from them.

**Comment by Zhuinden** [comment]
Theoretically `onZeroItemsLoaded` should trigger when you've reached the end, as the behavior itself is directly copied from PositionalDataSource in Room. 🤔

**Comment by stevepham** [comment]
@Zhuinden , could you please give me advice if I implement monarchy the right way. Here is my implementation:
`val realmSource = monarchy.createDataSourceFactory(....) // query realm` 
`val dataSource = realmSource.map {  } // Some mapper between entity and model`
// Set some config and boundary here
`val pageList = LivePagedListBuilder<Int, Model>(dataSource, PagedList.Config.Build()`
`monarchy.findAllPagedWithChanged(realmSource, pagedList)` 
// Is it correct for get paging data from realm
`
Thanks.

**Comment by Zhuinden** [comment]
That sounds right, so if I find some free time I'll try to look at whether newer versions of Room implement some magic tricks to manually get an instance of a boundary callback to invoke it or something, I expected this to be handled internally within Paging though.

**Comment by stevepham** [comment]
Hopefully looking forward you 👍 for this case

**Comment by Zhuinden** [comment]
I'm sorry, I never figured out why it doesn't work. :/

**Comment by stevepham** [comment]
So I'll close this
