### ISSUE TITLE
Update to Realm 10.0.0

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/realm-monarchy#34]
I killed Paging 2 integration, released 1.0, and Realm 10 comes out. 👀

I wonder what the version against that version should be.

**Comment by NightDeveloper-wq** [comment]
When will you be released for Realm 10?

**Comment by Zhuinden** [comment]
Now

https://github.com/Zhuinden/realm-monarchy/commit/8149cad681bdb8d254a469098d3e3537ea4ccde6
